apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
        - name: inventory-management
          image: <your_azure_container_registry>/inventory_management:latest
          ports:
            - containerPort: 3001  # Assuming the inventory_management service runs on port 3001
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001  # Matches the containerPort in the deployment
  type: LoadBalancer
